### ISSUE TITLE
Using Altair UI while not connected to the internet 

### ISSUE THREAD

**Issue by atodkar2** [graphql-dotnet/server#1005]
I would like to use the Altair UI in our internal application where the system is not connected to the internet. Bu I see there are static files which are being loaded from internet when the UI is opened. Is there a way to cache these dependencies offline? Can we use this UI while not connected to the internet?

**Comment by sungam3r** [comment]
Each UI package has options class and `IndexStream`/`PostConfigure` properties to achive that. For Altair - https://github.com/graphql-dotnet/server/blob/master/src/Ui.Altair/AltairOptions.cs#L31-L37

**Comment by Shane32** [comment]
Altair is an open-source UI and can be installed locally within your web server.  Please visit https://altairgraphql.dev/ for details.  Although it is possible to modify the Altair plugin provided here with custom HTML (and thereby changing the dependencies to be served locally), such behavior is outside the design goals for this project.  For example, you would certainly need to load those dependencies on your web server or write additional middleware to serve the additional files.  At that point, it is likely that the entire Altair UI would be served through the same means (MVC, pages, static files, whatever) rather than using this middleware at all.

**Comment by sungam3r** [comment]
Closed as answered.
