### ISSUE TITLE
Playground running on /graphql

### ISSUE THREAD

**Issue by tsteele** [graphql-dotnet/server#175]
On the pre-release version, we had configured the path for playground to be /graphql/ui/playground which worked fine. 
This was done to have a single endpoint of our api gateway for grapghql.
However on the latest version this does not work anymore , it appears all requests are routed to the graphql engine, including graphql/ui/playground.
So when you try to run playground , you get the error "GraphQL.ExecutionError: A query is required"

Is there any way we could keep our current playground path with the new release?

**Comment by johnrutherford** [comment]
The `GraphQLHttpMiddleware` uses `PathString.StartsWithSegments()` to match the request path. I suppose this could be changed to use ‘Equals()`, but it looks like `StartsWithSegments()` has always been used. 

As a workaround, if you add the playground middleware to the pipeline before the graphql middleware, it should work how you intend because the playground middleware will match the path first.

**Comment by sungam3r** [comment]
@joemcbride @johnrutherford Do we want to change the current behavior? If so, then this must be done for all three projects - Playground, Voyager, Graphiql. It seems to me that the current behavior needs to be changed.

**Comment by KreativJos** [comment]
> The `GraphQLHttpMiddleware` uses `PathString.StartsWithSegments()` to match the request path. I suppose this could be changed to use `Equals()`, but it looks like `StartsWithSegments()` has always been used.
This is correct, because the path does not have to be an exact match. The only correct solution I see here is to add an option like `ExactPathMatch` to the GraphQLHttpMiddleware constructor.

> 
> As a workaround, if you add the playground middleware to the pipeline before the graphql middleware, it should work how you intend because the playground middleware will match the path first.

As far as I know, this is how middleware should be working - First one added should be executed first, second one second, etc.
This is also how the single-page applications are built - by going through all middleware and ending up in the 'catch all' middleware.

**Comment by sungam3r** [comment]
> because the path does not have to be an exact match

Could you please give an example?

**Comment by KreativJos** [comment]
> > because the path does not have to be an exact match
> 
> Could you please give an example?

Trailing '/', but that can be checked for specifically.
I had another issue regarding the path not being an exact match, but I cannot recall what it was at this time.

**Comment by sungam3r** [comment]
I mean, it seems strange that the middleware is triggering on the path `/graphql/blablabla/`, this is not correct if middleware was registered with `/graphql`.

**Comment by sungam3r** [comment]
> Trailing '/', but that can be checked for specifically.

I understand, but this is a trifle.

**Comment by KreativJos** [comment]
> > Trailing '/', but that can be checked for specifically.
> 
> I understand, but this is a trifle.

Correct. And I still cannot recall the other issue, so it most probably was no real issue. It might've been something like trimming spaces.

**Comment by sungam3r** [comment]
Will be resolved as part of #430 .

**Comment by sungam3r** [comment]
@tsteele #440 was merged in `develop`. You can download preview packages [here](https://github.com/orgs/graphql-dotnet/packages?repo_name=server). Could you check your case?

**Comment by sungam3r** [comment]
v5 was published
