### ISSUE TITLE
Fragments in subscriptions

### ISSUE THREAD

**Issue by XREvo** [graphql-dotnet/server#258]
Hi,

First of all, i'm honestly sorry if i've missed something or if i'm doing something incorrectly. Don't hesitate to correct me.

I was playing with the `Samples.Server` project, and i was trying to use a fragment on a subscription. But it always fail when i'm referencing a fragment.
![01  Fail to subscrive](https://user-images.githubusercontent.com/234101/64285141-6d0c3180-cf5b-11e9-8188-e64411e1d138.png)

If i remove the fragment, everything goes back to normal. I can add message and seeing them coming.
![02  Succeed to subscribe](https://user-images.githubusercontent.com/234101/64285232-a6dd3800-cf5b-11e9-9c76-4fa6ab07e0f5.png)

Is it allowed to use fragment in subscription?

Thank you for your help
And by the way, thanks to all contributors (this library is awesome)

**Comment by sungam3r** [comment]
NRE is always considered as a bug.

**Comment by Shane32** [comment]
Fragments are tested to work correctly with subscriptions in GraphQL.NET Server version 7.

However, Playground does not send a unnamed subscription containing a fragment over a WebSocket connection.  This bug is tracked in these places:
- https://github.com/graphql/graphql-playground/issues/1067
- https://github.com/apollographql/graphql-subscriptions/issues/178

The solution is to name the subscription.  In the above sample, just change `subscription {` to `subscription test {` and it will work.

The NRE bug in version 6 was due to GraphQL.NET Server attempting to execute a subscription request over HTTP POST, which is impossible.  Now the proper error message is returned, as shown below:

```json
{
  "error": {
    "errors": [
      {
        "message": "Subscription operations are not supported for POST requests.",
        "locations": [
          {
            "line": 1,
            "column": 1
          }
        ],
        "extensions": {
          "code": "HTTP_METHOD_VALIDATION",
          "codes": [
            "HTTP_METHOD_VALIDATION"
          ]
        }
      }
    ]
  }
}
```
