### ISSUE TITLE
Fluent authorization policy definition

### ISSUE THREAD

**Issue by corstian** [graphql-dotnet/server#293]
Recently I have built a way to add authorization policies in a fluent way to a `GraphType` using ASP.NET's `AuthorizationPolicyBuilder`. As this code is heavily inspired on the `AuthorizationValidationRule` as found in this repo I was wondering whether there would be any interest in merging this code back in here for stability/accessibility reasons. The code is currently available in a testbed of mine, which does not really have a stable API surface.

The takeaway is that authorization policies can be defined in the following way:

```csharp
Field<Metar>()
    .Name("metar")
    .WithPolicy(policy => policy
        .RequireAuthenticatedUser()
        .RequireAnyScope("all:weather"))
    .Resolve(c => new { });
```

A blog post explaining the method is available here: https://corstianboerman.com/2019-12-16/graphql-dotnet-authorization.html.

**Comment by sungam3r** [comment]
Would you like to post PR?

**Comment by corstian** [comment]
Sure, if there's interesting in adding this I'll work something out!

**Comment by sungam3r** [comment]
PRs are welcome.

**Comment by zaneclaes** [comment]
@corstian this looks like exactly what I want. Please do consider PRing it into the main repo.

**Comment by corstian** [comment]
I just checked whether it is possible to do so; the primary blocker right now seems to be the storage of authorization policies by a string identifier.

The way my approach works is to store an `AuthorizationPolicy` type within the nodes metadata, instead of a list of available authorization policies. If I were to implement this method in the current code base as is I believe that could/would lead to a significant amount of confusion.

The way it could be done is to mix both approaches, allowing for global identifiers to be mixed with locally defined authorization policies, though I'm currently unable to oversee the consequences of such approach.

**Comment by sungam3r** [comment]
@corstian Thanks for you interest. I finally took the time to read old emails. I read your [blog](https://corstianboerman.com/2019-12-16/graphql-dotnet-authorization.html) and understood your motivation:

> In order to stay in line with the (fluent) code-first conventions for building a graph API, my aim is to be able to define the authorization policies right on the field definitions. This way the authorization rules would be grouped together with the resolver, and gives the **ability to quickly figure out what the authorization requirements are for a certain GraphType**.

Nevertheless, I cannot consider this approach as correct from the point of view of the separation of areas of responsibility. You need to understand that setting policies and applying policies are completely different activities. Policies are configured in named entities. In this place (application composition root, etc) we work with a variety of ASP.NET Core APIs. Next, we indicate in certain fields on GraphQL Schema which policies should be applied to them. We use the name of the policy for this. It's just a declaration. Your approach mixes areas of responsibility. Policies begin to be constructed on the field itself. There is tight coupling between different layers of the application - GraphQL schema layer and ASP.NET Core web hosting layer. They begin to act as a whole without the ability to change the auth engine implementation. Also, the obvious disadvantage of this approach is code repetition for the delegate building the policy:
```
policy => policy
        .RequireAuthenticatedUser()
        .RequireAnyScope("all:weather")
```

Of course, you can solve this problem by introducing many helper extension methods that will encapsulate the repetitive code. Basically, you will only create named policies implicitly without explicitly naming them.

>  I was wondering whether there would be any interest in merging this code back in here for stability/accessibility reasons.

Considering all of the above, the answer is no due to violation of SOLID principles although I will be glad to hear your thoughts.

**Comment by corstian** [comment]
I appreciate your effort in understanding the problem! I must agree that this screws over some SOLID principles, and therefore it's best to drop this issue here.

Regardless of that I'd be curious to hear your thoughts on consolidating authorization rules together with the resolvers. I found it to lower the cognitive load required to maintain resolvers, but thinking about it, I would also understand it could be a subtle code smell indicative of underlying architectural design flaws.

**Comment by sungam3r** [comment]
>  I'd be curious to hear your thoughts on consolidating authorization rules together with the resolvers.

First I'd prefer to keep validation separated from resolvers. Validation happens before execution stage. In your solution, the process is similar, with the only difference that the policies (not names) are placed in the fields themselves. In fact, this is the same meta information, we just use more dependencies. I almost always think about introducing additional dependencies as a disadvantage. Also, I should note that the current organization of the code does not match my idea of how dependencies should be laid out. We have two projects for authorization - this one + https://github.com/graphql-dotnet/authorization . They are very similar and do the same thing. Both have `AuthorizationMetadataExtensions` class. The problem is that, in essence, this class should not be located inside these projects. The problem is not so much duplication as it is to separate the declaration of authorization requirements from the authorization engine itself. I need to make a package named like GraphQL.Authorization.Core in the GraphQL.NET repo or even just place `AuthorizationMetadataExtensions` inside the GraphQL.NET repo. Then, in order to declare the requirements for authorization in the fields (indide schema), you do not need to reference a package with a specific implementation - be it ASP.NET Core integrated one or https://github.com/graphql-dotnet/authorization or anything else. @joemcbride we already talked about the consolidation of two projects. I believe this is the first mandatory step towards this.

**Comment by corstian** [comment]
Thanks for sharing your thoughts! Regarding these packages, back when I started out using GraphQL that had been a major source of confusion for me. Looking forward for any changes in this space!
