### ISSUE TITLE
Authorization via IValidationRule

### ISSUE THREAD

**Issue by Ekkeir** [graphql-dotnet/server#314]
We're using graphql-server in production and had to deal with implementing authorization. There're some observations and impressions.

1. While IValidationRule seems a convenient place to implement authorization - any execution can be prevented on failed authorization, there's already an error reporting mechanism, we can check for query validation errors before performing authorization too - still, it seems to be placed a bit too deep in the innards of GraphQL libraries. For instance, I failed to find any definitions for `ObjectField` as compared to `Field`, there were suddenly `Nodes`, `FieldDefinitions`, `FieldTypes`, `Operations`, `OperationTypes` etc. to deal with and to make sence of (if there's an extensive documentation for those - would love to see it). My point is - it would be great to have a simpler (dedicated?) and more straightforward API for dealing with authorization needs.

2. Our authorization process, besides the poicies and authentication sometimes is query arguments-dependent. As such, it would be great to have `ResolveFieldContext<T>` (seems to be to-go-to way to access query arguments) availible for authorization. As of now we resorted to implementing our own and not at all elegant resolver in our IValidationRule.

3. Field middlewares seem quite close to the desired API - relative simplicity, `ResolveFieldContext` is availible and policies can be retreived via the context too. The obvious downside is that it's executed per field, that is (if I'm not mistaken) a part of query can pass authorization and execute and then some would not be authorized, which may lead to undesired outcomes especially when dealing with mutations). Due to graph-based nature of graphql, there's also a matter of policies being executed more than once (several fields with the same authorization policy). In cases where authorization is not without side-effects, those would have to be controlled (it seems quite doable though).

I hope there's some use to these thoughts.

**Comment by sungam3r** [comment]
1. Could you specify your proposal? It would be nice to see API example.
2. Validation stage and Execution stage are two different stages while serving GraphQL request. `ResolveFieldContext<T>` exists **only** for execution stage after validation completes. Nevertheless, I understand that you may lack some convenient APIs, this brings us back to question 1.
3.
>  a part of query can pass authorization and execute and then some would not be authorized, which may lead to undesired outcomes especially when dealing with mutations

Why? You have complete control over the Field Middleware behavior.

**Comment by Ekkeir** [comment]
1. I don't have a clear vision for such an API, at the moment it seems quite like ExecutionMiddleware, but all fields are traversed before the actual query/mutation execution (Preexecution Middleware?). And such middleware would be able to accumulate errors in some way and report them all combined like it happens for validationErrors.

A slighly more complex approach, it seems, would be to implement it as some INodeVisitor.

2. It would be great to have something like `ResolveFieldContext<T>`'s method  `GetArgument<T>` available when implementing `IValidationRule`.

3. Imagine a mutation with several levels of fields. Top level field authorization happens in field middleware and succeeds, some resolver logic happens. Then a deeper field is reached, field middleware fires up again, authorization is not passed for the deeper field, but, alas, higher level field has already been executed.

I think I'd better provide some examples of complexity when implementing authorization via IValidationRule that do not seem perfectly understandable.

Take [AspNetCore Authorization](https://github.com/graphql-dotnet/server/blob/develop/src/Authorization.AspNetCore/AuthorizationValidationRule.cs#L63-L66) for example.
Intuitively authorization seems to be straighforward enough. We've got some fields combined into a graph, we have to traverse the graph and check some metadata for each encountered field.
And yet there're: 
`Operations`, where you do the following `context.TypeInfo.GetLastType()`
ObjectFields`, where you do the following (esentially) `((IComplexGraphType)context.TypeInfo.GetArgument().ResolvedType.GetNamedType()).GetField(objectFieldAst.Name)`
`Fields`, where there's not one, but two types to consider for authorization:
- `context.TypeInfo.GetFieldDef()`
- `context.TypeInfo.GetFieldDef().ResolvedType.GetNamedType()`

For each type there's a different way to obtain the authorized type deep within GraphQL.net.

While in execution middleware it seems to boil down to the following (via `ResolveFieldContext`)
`context.FieldDefinition.GetPolicies()`.

**Comment by HrvojeFER** [comment]
@Ekkeir 

I like the idea of having a clear API for Authorization handling, however, I think that if any part of a query is not authorized, the whole query shouldn't be resolved and an error should be thrown. If only parts of a query would be resolved it would break ACID (atomicity, specifically) as queries wouldn't truly be atomic. Such queries would be much harder to debug and test in a lot of situations.
I can see some benefits to doing this, but maybe this is yet another reason why we need this kind of API because people like me and you have different opinions about this and we would like to do things differently.

About the authorization implementation. 
I am having a hard time implementing authorization at my workplace. I am currently trying to migrate an ASP.NET Core server from a REST API to a GraphQL API and everything seems to be relatively easy except for the authorization part. I already have everything set up for authentication and authorization with IdentityServer4 including an authorization policy for the REST API, however, there seems to be no clear answer for doing the same for a GraphQL API. I would like to apply the same authorization policy for a whole scheme (or for all types, queries and mutations on a scheme) with the option to change this for certain types, queries and mutations in the future. 
Would any of you be willing enough to provide some code examples? I am still new to GraphQL, so some code samples would be greatly appreciated. Initially, I was going to use the code from the already provided samples, but I don't understand how to apply them to my situation. Currently, I am thinking about adding app.MapWhen to Startup.Configure for the "/graphql/scheme" endpoint and adding authorization logic specifically for GraphQL there, but I was wondering if there was a simpler solution. 
Thank you in advance for the help. I would be willing to provide my solution to the problem because IdentityServer4 + ASP.NET Core and some authorization policies seem like a popular solution for authentication/authorization of client applications and because of that, I think that other people would find it useful.

**Comment by sungam3r** [comment]
Maybe related to discussions in https://github.com/graphql/graphql-over-http/pull/125 and https://github.com/graphql/graphql-over-http/pull/79

**Comment by Shane32** [comment]
@Ekkeir It seems like you're requesting an easier way to implement `INodeVisitor` / `IValidationRule`.  These comments have merit, but are harder to implement than it would appear.  There is a new `IVariableVisitor` but that really doesn't cover your suggestion.  I would have to say this is a 'known issue' of GraphQL.NET, which makes it extremely difficult to implement variable-dependent validation rules.

Also, based on your comments it would seem that it would be beneficial to add `IResolveFieldContext.User` so resolvers have easy access to the `ClaimsPrincipal` without a lot of workarounds.  Not sure if this is exactly what you had in mind, but I think this would certainly be useful.  Adding this property would be easy and should have no notable drawbacks.  cc: @sungam3r 

> EDIT: I figured out how to add authorization. I didn't know there was the AddGraphQLAuthorization method. 🤦‍♂️
> @sungam3r Could you just mention in the readme.md for the repo that there exists such a method?

The readme file for GraphQL.NET Server v7 should cover authorization well, including authorization over WebSocket connections.  Authorization capabilities are greatly enhanced in v7.

**Comment by sungam3r** [comment]
`HttpContext` is from ASP.NET Core world, `IResolveFieldContext` not

**Comment by Shane32** [comment]
`IPrincipal` is a .NET standard interface since .NET Framework 1.1 and is not a part of ASP.NET.  And `IResolveFieldContext` is conceptually the same as `HttpContext` -- both provide contextual information about the currently executing request.  I don't understand the difference.

Example:

| HttpContext | IResolveFieldContext | Description |
|-|-|-|
| Request.QueryString | FieldAst | The node/path being executed |
| Request.Form | Arguments | Parameters for the request |
| RequestAborted | CancellationToken | Signals when the request should be aborted |
| RequestServices | RequestServices | DI services for the request |
| Response | Errors / Extensions | Response data |

Basically these classes serve the same purpose.  `User` is completely appropriate for `IResolveFieldContext` from that point of view -- it provides access to the security principal that was authenticated (if any) for the request.

`IPrincipal` is a .NET standard interface, just like `IObservable`, `IServiceProvider`, `IList` and so on.  It does not mean that anyone is required to use it.  But in this case, for an additional 8 bytes of memory per request, I would think we should add support within `IResolveFieldContext`.

Now of course we could segment the fields within `IResolveFieldContext`, such as adding an `Execution` property that returns `IExecutionContext` which would contain the user.  This might be better than continually adding properties to `IResolveFieldContext`.  But so far we have not done so, and all the properties of the execution context are added to the field context so they can be accessed.

**Comment by sungam3r** [comment]
OK. I told about not `IPrincipal` itself but about `HttpContext` as a source of principal object. And I would prefer `IPrincipal` over `ClaimsPrincipal` as a type of new property.
