### ISSUE TITLE
Support for graphql-net version 3.0... ??

### ISSUE THREAD

**Issue by aleGuardiola** [graphql-dotnet/server#357]

**Comment by BenjaBobs** [comment]
There are preview packages on MyGet that use preview versions of `graphql-dotnet`
![image](https://user-images.githubusercontent.com/8708965/79949590-10bc3a80-8476-11ea-8c22-2e81c95e9e66.png)

But since this is a recurring question ("How to access newest version/features") maybe the CI/CD flow should be restructured to also release to NuGet, or maybe the readme should have a section in the top recommending the MyGet version and describing setup of it?

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/79976419-3e6ca800-84a5-11ea-932e-b345e6665653.png)

**Comment by sungam3r** [comment]
@BenjaBobs Are you OK whis these changes?

**Comment by aleGuardiola** [comment]
Thank you very much for this, yeah I am good with this changes. I am developing a library to create the graphql api but I was using version 3.0 and I wanted to tested out with the server let me check if it works now. Maybe you guys can check it out and tell me what u think: https://github.com/aleGuardiola/Graphql-Controller

**Comment by BenjaBobs** [comment]
Looks good to me. Also didn't know about fuget. TIL. :)
