### ISSUE TITLE
IResolveEventStreamContext.RequestServices is null when subscribe start

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/server#547]
I would expect that property to be available here, maybe also with a scoped (as long that the subscriptions is live) service provider filled. 

Ive looked into the codebase but did not find the right codepath here where the could be done. Maybe someone could give a hint.

**Comment by machship-bsuryn** [comment]
I'm also interested in this, we have set this in our `_documentExecuter.ExecuteAsync` options in our http method, but unsure where we need to set this for subscription and the IResolveEventStreamContext object

**Comment by Shane32** [comment]
Implemented in #691 

As of now, when a websockets-based graphql request is received, the GraphQL.NET code will create a service scope and execute the subscription resolver.  The service scope is disposed immediately once the resolver has completed (not when the observable completes, nor when the client disconnects).  This design assumes the returned `IObservable` is an object that broadcasts responses to multiple graphql clients.  Assuming this is so, a scoped service providing the observable doesn't really make sense.  So then I assumed it would need to be a singleton.  Of course within the singleton a scope could be created to utilize scoped services, but this is not handled by GraphQL.NET.

The reason a service scope is created at all is because the nature of WebSockets is such that multiple subscription requests may be received over a websockets connection at the same time.

**Comment by Shane32** [comment]
To clarify the situation, the child field resolver nodes still will not have access to a service provider; only the initial subscription field resolver has a scoped service provider (for reasons noted previously).  At this time, child field resolver nodes would need to pull singleton services from the constructor, or create their own service scope.
