### ISSUE TITLE
Question: When working with Scoped services

### ISSUE THREAD

**Issue by samyhrer** [graphql-dotnet/server#56]
This is not an issue, just a general question I hope someone can provide some insight for.

We are currently trying to create a Graphql endpoint with an Entity Framework based service layer. Furthermore we try to utilize Dependency Injection in order to inject the dbContext in our Mutation-, Query- and Subscription-implementations. Using Dependency Injection has although proven difficult as the injected dbContext is Scoped by nature. This seems to conflict with how this library require(?) that everything is registered as a Singleton. That said, I believe I've solved it for the HTTP-middleware by creating a custom HTTP-Middleware where the Schema is resolved in the Invoke-method instead of the constructor. The WebSocket-Middleware is although a bit more complicated, and we've not found any elegant solutions to this. 

So any advice on using Subscriptions together with a Schema that relies on scoped dependencies will be much appreciated.

**Comment by ntaranov** [comment]
Hi, I was migrating from using a controller action to middleware and encountered the same issue, here are my 2 cents. 

Controllers are created on per request basis while middleware instances are created as singletons by default. 

I'm using standard .net core ID and problem seems to be as follows. 
1. You inject something referencing EF DB context somewhere fields' resolver functions. 
For me it was DbQuery which referenced scoped DB context. 
2. Middleware singleton is created, all the types needed for this are resolved and all objects needed for the creation of the sigleton are instantiated. 
3. Middleware references schema and sets it in constructor forever. 
4. Schema references Query and Mutation, they are resolved once and forever when schema is created. 
5. As fields are added in Graph types constructor, this effectively means constructor injection for fields. 
6. As a result no matter how you register your dependecies, DB context is going to be resolved and instantiated only once, when the middleware singleton is created. 
7. As a result, all requests share 1 instance of DB context on server, and as soon as 2 HTTP requests arrive with little time in between, and exception is thrown. 

Implementing you own middleware, using ISchema method injection in Invoke is going to result in Shema being resolved on every request. This will result in a bit worse performance, but the main problem is that the solution might not guarantee DB context concurrency safety. 

I appears that fields [are opinionated](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L328) about if their resolve functions are executed in a single thread or not.

For instance, ComplexGraphType's FieldAsync method has [resolver type of SlowFuncFieldResolver](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ComplexGraphType.cs#L138), 

which might lead to [creating new tasks](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Resolvers/SlowFuncFieldResolver.cs#L27) to be executed possibly in a separate thread.

Of course, different software has different requirements and there is no good general solution for DB Context management for all possible GraphQL fields trees. 

I personally decided to go with injecting a factory(DbQueryFactory) instead of DbQuery.
I call queryFactory.GetQuery() in all places where I used query before. The factory is responsible for managing the query lifetime. 

Maybe,  as this approach is about injecting factory to resolver functions, it will help you with Subscriptions too.

**Comment by samyhrer** [comment]
@ntaranov thanks for your feedback! I'll look into the strategy of injecting a factory instead. Got the Subscription part working by creating custom implementations (only with minor changes) of GraphQlWebSocketrsMiddleware, GraphQlEndpoint and SubscriptionProtocolHandler. I'm basically passing the schema all the way down from the Middlewares Invoke method to wherever it is needed. But the solution feels forced, and comes with the drawbacks you mention :/

**Comment by pekkah** [comment]
I would recommend a factory pattern also. At the moment the type system is built so that it leans towards singletons and building the schema per request would be too much.
