### ISSUE TITLE
GraphQL endpoint throwing HTTP 500 on HTTP GET

### ISSUE THREAD

**Issue by sharppanda** [graphql-dotnet/server#583]
## Description

The graphQL server throws an InvalidOperationException("Cannot execute request if no query is specified") when HTTP GET is requested on graphql endpoint.

This is a very common scenario (people opening the graphql endpoint in browser). It is causing an internal server error. It would be better if the GraphQL framework could handle this situation. Instead the error is propagated to ASP.NET middleware.

### Steps to reproduce

Open url `http://{server}/graphql` in browser which points to the graphql endpoint.

### Expected result

Bad http request (400)

### Actual result

Unhandled exception is thrown.
Returned Http Response 500.

**Comment by Shane32** [comment]
I misunderstood your original issue.  At "second glance" I would agree with your assessment -- it should calmly return 400 rather than throwing an internal server exception.  Is it possible for you to create a PR to fix the behavior?  We typically start by adding a failing test to demonstrate the issue, then implementing a fix and verifying that the test passes.

@sungam3r If you have time to review this issue, that would be appreciated.

**Comment by sharppanda** [comment]
There are two ways to fix it.

Either in middleware (try catch) or the `DocumentExecuter.ExecuteAsync` could return it using `ExecutionResult` if `options.ThrowOnUnhandledException` is false.

Which way would you prefer?
