### ISSUE TITLE
Document caching and AuthorizationValidationRule

### ISSUE THREAD

**Issue by langtu** [graphql-dotnet/server#596]
When use document caching (`MemoryDocumentCache`), `DocumentExecutor` only check `CachedDocumentValidationRules` if cache hit [(more),](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L95) and the authorization process (that added `AuthorizationValidationRule`) will ignore between requests.

Currently, there's no way to set `CachedDocumentValidationRules` in `DefaultGraphQLExecuter<>`. Should we allow to config `ExecutionOptions`'s `CachedDocumentValidationRules` in `GraphQLOptions` as other options [here](https://github.com/graphql-dotnet/server/blob/master/src/Core/DefaultGraphQLExecuter.cs#L56)?

**Comment by Shane32** [comment]
For now you can derive a class from `DefaultGraphQLExecuter<>` and set the properties accordingly.

In the next version, the `IGraphQLBuilder` interface will be moved into the main project, and includes an `IConfigureExecution` interface which allows `AddValidationRule` to install the rule into the execution rather than all registered instances being pulled from dependency injection within `DefaultGraphQLExecuter`.  There is a new boolean argument to specify whether the validation rule applies to cached documents.

Sample signature:
```cs
public static IGraphQLBuilder AddValidationRule<TValidationRule>(this IGraphQLBuilder builder, bool useForCachedDocuments = false)
    where TValidationRule : class, IValidationRule
```

With the new capabilities within `IConfigureExecution` and `IConfigureSchema`, the `IGraphQLExecuter` interface is rather pointless and `IDocumentExecuter` should be used directly.  `DefaultGraphQLExecuter` is deprecated because it would install the validation rules a second time during execution.

Please let me know if you are interested in testing the beta version and providing feedback before release.  The upcoming release will be the last version before the next major version.

Links:
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2571
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2605
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2606
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2607
- https://github.com/graphql-dotnet/graphql-dotnet/pull/2612
- https://github.com/graphql-dotnet/server/pull/602
