### ISSUE TITLE
GraphQL.Server.Transports.AspNetCore.SystemTextJson did not respect "JsonSerializerOptions"

### ISSUE THREAD

**Issue by WillLiu-Eclipse** [graphql-dotnet/server#603]
In my graphql project, I have some json document that contains "string" number, like "NaN".
And I keep getting 
`.NET number values such as positive and negative infinity cannot be written as valid JSON.` exception.

After some investigation, I found that there is one setting called "NumberHandling" which can perfectly handle this issue.
Then I try to set it by adding some serializer settings
```
            .AddSystemTextJson()
                configureDeserializerSettings =>
                {
                    configureDeserializerSettings.NumberHandling = JsonNumberHandling.WriteAsString | JsonNumberHandling.AllowNamedFloatingPointLiterals;
                },
                configureSerializerSettings =>
                {
                    configureSerializerSettings.NumberHandling = JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals;
                })
```

After all I still getting the same error.

More details about the "Number Handling" in here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-invalid-json?pivots=dotnet-5-0

**Comment by Shane32** [comment]
The deserializer is not going to know which strings are supposed to be numbers or not, so the setting may not have any effect on GraphQL.  You will need to customize the scalar type so that it interprets strings as numbers.  Then you need to replace the intrinsic `FloatGraphType` with your own.  The below link demonstrates replacing the `BooleanGraphType` with a copy that interprets 0 and 1 as booleans as well as true and false.

https://graphql-dotnet.github.io/docs/getting-started/custom-scalars#replacing-built-in-scalar-types

Serialization might work as expected with the "write as string" option, but may not due to some performance-optimized code within the document writer.  In any case, when you customize the scalar as shown above, you can alter the serialization of values as well.

You may need to replace as many of the numeric scalar types as you use within your schema.  But you will not need to change any other of your code.

**Comment by Shane32** [comment]
This issue is not applicable to v6 or v7 as the server project as of v6 relies on the serializers provided by GraphQL.NET.  Please review the documentation within GraphQL.NET for configuration of the serializers.
