### ISSUE TITLE
Get rid of bodyGQLBatchRequest / bodyGQLRequest in GraphQLHttpMiddleware

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#717]

**Comment by Shane32** [comment]
Note: `_serializer.ReadAsync<IList<GraphQLRequest>>(httpRequest.Body, cancellationToken);` (versus `GraphQLRequest[]` or `IEnumerable<GraphQLRequest>`) allows for least allocations overall, since the serializer can deserialize a single item in an array, or multiple in a List, and either way a `for` loop can be used to iterate.

**Comment by Shane32** [comment]
This code has been updated for version 7. `bodyGQLRequest` and `bodyGQLBatchRequest` still exist internally within `InvokeAsync` only, so the external API has been cleaned up.

I suggest closing this issue.

**Comment by sungam3r** [comment]
I doubt I remember what I wanted.
