### ISSUE TITLE
How can I enable authentication for some resolvers but not others?

### ISSUE THREAD

**Issue by justinmchase** [graphql-dotnet/server#833]
I would like to be able to call `/graphql` with authentication for _some_ resolves but not another.

I've created an `@auth` directive which wraps the resolver of various query fields but not all of them. Ideally the HttpContext.User would just be `null` or not but it seems like it throws 401's before ever getting to the resolver.

I think if graphql was installed as an endpoint using `.UseEndpoints()` then it would be able to setup an anonymous endpoint by default but it seems to be installed as a middleware which maybe can't?

I'm not totally sure but this is what I was hoping for:
```cs
public void Build(IEndpointRouteBuilder builder)
{
    builder.MapGet($"/graphql", GraphQL).AllowAnonymous();
}
```

**Comment by Shane32** [comment]
Can you explain a little more about what determines when it needs authentication and when it doesn’t?

**Comment by justinmchase** [comment]
```gql
type Query {
  example1
  example2 @auth
  example3 @auth(policy: 'example')
}
```

So for example, if I have the above schema, I want `example1` to be callable anonymously. Meaning, a user could call without an `Authorization:` header at all.

`example2`, the user would have to provider a valid bearer token in the authorization header, but no roles are enforced.

`example3`, the user must provided a valid bearer token and the roles must match the policy.

So examples 2 and 3 work as expected _or_ example 1 can work as expected but I can't seem to figure out how to make them both work simultaneously.

My configuration step looks something like this:
```cs
IApplicationBuilder app;

app
  .UseAuthentication()
  .UseRouting()
  .UseAuthorization()
  .UseEndpoints(endpoints => ...)
  .UseGraphQL<Schema>()
  ;
```

In my `.UseEndpoints()` configuration I am able to configure other routes to be anonymous with `endpoints.MapGet($"/example", Example).AllowAnonymous();`.

If you allow anonymous, the User can still be set on the context but it can also be null. 

The `@auth` resolver users some logic like:

```
var http = context.RequestServices!.GetRequiredService<IHttpContextAccessor>();
var user = http.HttpContext.User;
if (user == null) throw new AuthenticationException();

var authorizer = context.RequestServices!.GetRequiredService<IAuthorizationService>();
var res = await authorizer.AuthorizeAsync(user, null, "ExamplePolicy");
if (!res.Succeeded) throw new AuthorizationException();
```

**Comment by justinmchase** [comment]
Also, while I can get the altair middleware to work by just positioning it before the `.UseAuthentication()` configuration, the docs do not work anonymously. That's a thornier issue since I can't apply my directive to the introspection api even if I wanted to.

**Comment by Shane32** [comment]
Are you using schema-first or type-first for your schema?

**Comment by justinmchase** [comment]
code first

**Comment by Shane32** [comment]
How are you defining and using the directive?  There are two different types of directives "schema directives" and "operation directives".  See https://www.apollographql.com/docs/apollo-server/schema/directives/#schema-directives-vs-operation-directives .  GraphQL.NET allows defining schema directives on types (graph types, field types, etc), but the `Directive.Validate` method is only executed when the schema is validated, and intended to validate the definition of the directive.  The directive is stored as metadata and you would need to write a validation rule to check that the type or field meets the authentication requirements defined in the directive.

But you do not need to define your own directive or validation rule; GraphQL.NET and GraphQL.NET Server provides the necessary infrastructure to set up authorization rules.  Simply call `AuthorizeWithPolicy` on the graph type or field type that you are applying a policy restriction to.  For example:

```cs
internal class QueryGraphType : ObjectGraphType
{
    public QueryGraphType()
    {
        // example 1 in your sample
        Field<StringGraphType>("test", resolve: _ => "It works");

        // example 3 in your sample
        Field<StringGraphType>("hero", resolve: _ => "John doe")
            .AuthorizeWithPolicy("MyPolicy");
    }
}
```

Then add the validation rule:

```cs
services.AddGraphQL(b => b
    .AddSchema<MySchema>()
    .AddGraphQLAuthorization()
    .AddSystemTextJson());
```

Now unfortunately the current version of GraphQL.NET Server does not support the following methods on GraphQL types and definitions:
- `AuthorizeWithRole()`
- `Authorize()` (example 2 in your sample)
- `AllowAnonymous()`

So for the moment, you would configure your schema by applying `AuthorizeWithPolicy()` to any graph types or fields that need authorization, while anything else would allow anonymous access.

In order to workaround example 2, you will need to define an authorization policy like this:

```cs
options.AddPolicy("Example2", x => x.RequireAuthenticatedUser());
```

In the new version of GraphQL.NET Server (v7), `AllowAnonymous()` will allow you to mark a type as having authorization requirements, which are skipped if all requested fields within the type are marked with `AllowAnonymous()`.

See #803 for a list of all the features that the new validation rule will have once merged and released.

The new version of GraphQL.NET will also support setting connection-based authorization rules.  This would not apply to you as you need to allow anonymous access to your endpoint.

**Comment by justinmchase** [comment]
AuthorizeWithPolicy is exactly what we are looking for.

We end up implementing the directive anyway because we're also modifying the description on the fields with information about the policy, but thanks.

Also, I realized that the issue with requiring authentication before even getting to GQL is essentially not related to this library at all, its essentially a middleware we have which can be swapped out to essentially handle authentication differently if I so choose.

So thanks for all the detailed replies it was super helpful!
