### ISSUE TITLE
Graphql Error

### ISSUE THREAD

**Issue by Hemant2384** [graphql-dotnet/server#839]
Hi! I was implementing Graphql with dotnet core and faced an error while Querying which says,

**GraphQLMIddleware.Startup[0]**
**Expected an IEnumerable list though did not find one. Found: AsyncStateMachineBox`1 occurred**

Please Can anyone help me through this?

This my **Startup.cs**

```C#
 string connectionString = Configuration.GetConnectionString("SampleAppDbContext");
            services.AddDbContext<ProductContext>(options =>
                      options.UseSqlServer(connectionString));
            services.AddScoped<MySchema>();
            services.AddScoped<MyQuery>();
            services.AddScoped<ProductRepository>();
            services.AddGraphQL(b => b
            .ConfigureExecutionOptions(options =>
            {
                var logger = options.RequestServices.GetRequiredService<ILogger<Startup>>();
                options.UnhandledExceptionDelegate = ctx =>
                {
                    logger.LogError("{Error} occurred", ctx.OriginalException.Message);
                    return Task.CompletedTask;
                };
                var enableMetrics = Configuration.GetValue<bool>("EnableGraphQLMetrics", false);
                options.EnableMetrics = enableMetrics;
            })
            .AddSchema<MySchema>(GraphQL.DI.ServiceLifetime.Scoped)
            .AddSystemTextJson()
            .AddErrorInfoProvider()
            .AddWebSockets()
            .AddGraphTypes(typeof(MySchema).Assembly) // registers graph types with transient lifetimes
            .AddDataLoader()
            .AddHttpMiddleware<MySchema>()
            .AddWebSocketsHttpMiddleware<MySchema>());
            services.AddCors();
```

**Comment by Shane32** [comment]
Can you list all of the nuget packages that start with `GraphQL` you have installed, and what versions they are?

Is this a new GraphQL.NET project or upgrading from an older version?

**Comment by Hemant2384** [comment]
Please Can I ask you me in two three more doubts?

**Comment by Hemant2384** [comment]
I was so much struggling in implementing with newer versions of the packages. You know Shane, then I went through all your repos and looked through your implementations and finally I am able to work with it.

**Comment by Shane32** [comment]
If you have any questions, please ask.

**Comment by Shane32** [comment]
1.  Yes; the AddHttpMiddleware is ASP.NET Core middleware which intercepts HTTP requests for the configured url and executes the graphql request, and returns the response.  It is provided so you do not need to write a MVC controller action (or similar) to parse and execute GraphQL requests or serialize GraphQL responses.  That middleware is the main purpose of this nuget package.  You may use GraphQL.NET without this Server nuget package if you wish, but then you need to write your own code to read and deserialize a request, execute it, and serialize and write the response.

2. Generally yes.  If you want to benefit from all of the code within `GraphQLHttpMiddleware` and just extend it a bit (as in the `GraphQLHttpMiddlewareWithLogs` sample), then yes you would derive from that class.  However, you may write your own ASP.NET Core middleware from scratch without the use of this nuget package at all.

3. `AddHttpMiddleware` actually just registers the middleware in the dependency injection engine so that it can be referenced by `app.UseGraphQL` later.  In the upcoming version of GraphQL.NET Server (v7), you will not need `AddHttpMiddleware` at all.  You will also be able to remove `AddWebSocketsHttpMiddleware` and `AddWebsockets`, and websocket support is built into the `app.UseGraphQL` call.  This makes adding the HTTP middleware as easy as adding a single line of code -- `app.UseGraphQL()`.

4. You should not need to write your own `GraphQLHttpMiddleware` class at all, unless there is some specific need that you cannot do with the default implementation.  There could be many reasons.  For example, you might want to log all queries that fail validation.  I would not create your own middleware until you have a need to do so.

Note that there is also GraphQL.NET "Field Middleware", which is completely different.  It intercepts execution of every field on your graph.  The most common use would be to record execution statistics on a per-field basis.

**Comment by Hemant2384** [comment]
Okay, Thankyou Thankyou so much for explaining me. Is there any repo which shows implementation of the ```IFieldMiddleware```, with the current version of GraphQL packages, because I was using the ```FieldMiddleware```, but when I tried to implement it was showing that the interface does not implements it.
I implemented as it was given in the docs,
```C#
var schema = new Schema();
schema.Query = new MyQuery();
schema.FieldMiddleware.Use(new MyMiddleware());
```
Error was,
```schema has no method as FieldMiddleware```

**Comment by Shane32** [comment]
Call `.AddMiddleware<MyMiddleware>()` with all the rest of your GraphQL registrations in Startup.cs.

**Comment by Shane32** [comment]
The sample you provided is valid; I do not know why it would not work for you.

See: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L118

**Comment by Hemant2384** [comment]
Okay Okay Thankyou so much for helping.

**Comment by Hemant2384** [comment]
Hi Shane, I had one more doubt. Please Can you help me in this.

So this is my ```InstrumentFieldsMiddleware.cs```,

```C#
using GraphQL;
using GraphQL.Instrumentation;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GraphQLMIddleware
{
    public class InstrumentFieldsMiddleware : IFieldMiddleware
    {
        public async ValueTask<object> ResolveAsync(IResolveFieldContext context, FieldMiddlewareDelegate next)
        {
            var metadata = new Dictionary<string, object>
            {
                {"typeName", context.ParentType.Name},
                {"fieldName", context.FieldDefinition.Name.ToString()},
                {"path",context.Path },
                {"arguments",context.Arguments }
            };
            var path = $"{context.ParentType.Name}.{context.FieldDefinition.Name}";
            using (context.Metrics.Subject("field", path, metadata))
            {
                return await next(context).ConfigureAwait(false);
            }
        }
    }
}```

Now, I am adding my services as 
```C#services.AddSingleton<InstrumentFieldsMiddleware>();```

And finally configuring the middleware as,

```C#
var schema = new Schema();
 schema.FieldMiddleware.Use(new InstrumentFieldsMiddleware());
```

Now, to capture my metrics, Will I use the ```ILogger``` to log my ```path```  variable?
Or, Suppose if I query, a field and add a break poirnt on my ```path``` variable, will it give me the value? But, I tried this and got no value.
Can you help me in configuring this, like how to study that metrics.

**Comment by Hemant2384** [comment]
I made some changes.
Just registered my Middleware in the schema like this.

```C#
public MySchema(IServiceProvider services, MyQuery query, InstrumentFieldsMiddleware middleware) : base(services)
        {
            Query = query;
            FieldMiddleware.Use(middleware);
        }
```
And I got the details in my Output screen.
This is so cool!!.

**Comment by sungam3r** [comment]
Initial issue is solved so closing this one.
