### ISSUE TITLE
HttpStatus Code on GRAPHQL_VALIDATION error

### ISSUE THREAD

**Issue by gao-artur** [graphql-dotnet/server#967]
Not sure if it's a bug or a misunderstanding of the spec. I'm migrating from 5.1.1 to 7.2.0 and found that in some cases, the HttpStatus Code changed from 200 to 400. For example, when the required field is missing from the query, I'm getting now BadRequest (400)

```
{
  "errors": [
    {
      "message": "Argument 'testInput' has invalid value. Missing required field 'name' of type 'String'.",
      "locations": [
        {
          "line": 1,
          "column": 52
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION",
        "codes": [
          "ARGUMENTS_OF_CORRECT_TYPE"
        ],
        "number": "5.6.1",
      }
    }
  ]
}
```

The [spec ](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationjson) for `application/json` says:

> Note: A status code in the 4xx or 5xx ranges or status code 203 (and maybe others) could originate from intermediary servers; since the client cannot determine if an application/json response with arbitrary status code is a well-formed GraphQL response (because it cannot trust the source) the server must use 200 status code to guarantee to the client that the response has not been generated or modified by an intermediary.

And also:
> Note: For compatibility with legacy servers, this specification allows the use of 4xx or 5xx status codes for failed requests where the response uses the application/json media type, but it is strongly discouraged. To use 4xx and 5xx status codes, please use the application/graphql-response+json media type.

**Comment by sungam3r** [comment]
@gao-artur You provided irrelevant parts of the spec. The problem is not about intermediary servers or content type. The problem is the data itself. @Shane32 pointed in the right direction. Since v7 server returns 4xx if data entry is empty, i.e. execution was not started at all that means some validation error or any other arbitrary server-side error BEFORE actual execution of GraphQL query.

**Comment by Shane32** [comment]
@sungam3r You may wish to read this section again https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationjson

@gao-artur is correct that 400 is "strongly discouraged" for well-formed GraphQL responses with the "application/json" content type.

> This section only applies when the response body is to use the application/json media type.
> 
> The server SHOULD use the 200 status code, independent of any GraphQL request error or GraphQL field error raised.

We are catering to the `application/graphql-response+json` content type and although we vary the response content type based on the Accept header, we do not have code that sets the status code based on which response content type was selected.

**Comment by sungam3r** [comment]
OK, too many combinations to remember.

**Comment by Shane32** [comment]
We can look at adding this feature.  (Specifically, that the response status code is dependent not only on the response but the selected content type.)  It would likely have to be in the next major version since it probably requires a redesign of some of the protected methods of the middleware.  I think ultimately we want to determine the response content type earlier in the middleware logic to allow for adjusting behavior throughout the pipeline, for example to support subscriptions over SSE.

**Comment by Shane32** [comment]
Done for v8.  By default it will follow GraphQL over HTTP spec and return 200 for `application/json` responses when there are validation errors.

**Comment by Shane32** [comment]
@jantar2b If you’re still having a problem here, please open a new issue. I’m not familiar with app.AddRoutesFromModules() so please link to the applicable documentation also. Thanks!
